name: Build Hutool

on:
  push:
    branches: [ v5-master ]
  pull_request:
    branches: [ v5-master ]
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '8'

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Upload hutool-all Jar
      uses: actions/upload-artifact@v4
      with:
        name: hutool-all
        path: hutool-all/target/hutool-all-*.jar
